default:
  # image specification necessary to have git available (?)
  image: cmp-registry.stzh.ch/gar-proxy/szh-connect/cmp-docker/k8s-ops:latest

stages:
  - deploy_prod
    
deploy-job-prod:
  # ausgeführt wenn Push auf Main branch
  stage: deploy_prod
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - git status
    # prepare pushing to GitHub
    - git fetch
    - git checkout main
    - git config --global user.email 'pipeline@stadt-zuerich.ch'
    - git config --global user.name 'pipeline'
    # push this to github
    - echo ${GITHUB_USER}
    - git remote add github https://${GITHUB_USER}:${GITHUB_TOKEN}@${GITHUB_REMOTE}
    - git push -uf github main

